In [4]:
import Pkg; Pkg.add("CSV")

    Updating registry at `~/.julia/registries/General.toml`


   Resolving package versions...


   Installed InlineStrings ── v1.3.2
   Installed SentinelArrays ─ v1.3.16
   Installed WeakRefStrings ─ v1.4.2


   Installed FilePathsBase ── v0.9.20


   Installed CSV ──────────── v0.10.7


    Updating `~/.julia/environments/v1.8/Project.toml`
  [336ed68f] + CSV v0.10.7
    Updating `~/.julia/environments/v1.8/Manifest.toml`


  [336ed68f] + CSV v0.10.7
  [944b1d66] + CodecZlib v0.7.0
  [48062228] + FilePathsBase v0.9.20
  [842dd82b] + InlineStrings v1.3.2
  [91c51154] + SentinelArrays v1.3.16
  [ea10d353] + WeakRefStrings v1.4.2


Precompiling 

project...


  ✓ SentinelArrays


  ✓ FilePathsBase


  ✓ InlineStrings


  ✓ WeakRefStrings


  ✓ CSV
  5 dependencies successfully precompiled in 8 seconds. 312 already precompiled.


In [5]:
using Images, FileIO
using DataFrames
using CSV
using Downloads

# P = Downloads.download("https://raw.githubusercontent.com/nassarhuda/easy_data/master/programming_languages.csv",
#     "programming_languages.csv")



In [6]:
#-------------Q1.1.1-------------

C = CSV.read("./ratings.csv", DataFrame);
#print(C)


100836×4 DataFrame
    Row │ userId  movieId  rating   timestamp  
        │ Int64   Int64    Float64  Int64      
────────┼──────────────────────────────────────
      1 │      1        1      4.0   964982703
      2 │      1        3      4.0   964981247
      3 │      1        6      4.0   964982224
      4 │      1       47      5.0   964983815
      5 │      1       50      5.0   964982931
      6 │      1       70      3.0   964982400
      7 │      1      101      5.0   964980868
      8 │      1      110      4.0   964982176
   ⋮    │   ⋮        ⋮        ⋮         ⋮
 100830 │    610   164179      5.0  1493845631
 100831 │    610   166528      4.0  1493879365
 100832 │    610   166534      4.0  1493848402
 100833 │    610   168248      5.0  1493850091
 100834 │    610   168250      5.0  1494273047
 100835 │    610   168252      5.0  1493846352
 100836 │    610   170875      3.0  1493846415
                            100821 rows omitted

In [7]:
#delete all the movies that have less than 15 ratings and get dimension
groupby(C, "userId")
n_users = sort(unique(C.userId)) #row correspond to userID, even if empty
n_row = size(n_users)[1]
groupby(C, "movieId")
C0 = combine(groupby(C, [:movieId]), nrow => :n_rating)
validId = filter(y -> y.n_rating >=15, C0)
X = filter( x -> x.movieId in validId[:, "movieId"], C)

groupby(X, "movieId")
n_unique_movie = sort(unique(X.movieId))#unique movie id correspond to column
n_column = size(n_unique_movie)[1]
X0= zeros(n_row,n_column )
for n in eachrow(X)
    mId = n[2]
    uId = n[1]
    rating = n[3]
    column = findfirst( x -> x == mId, n_unique_movie )
    X0[uId, column] = rating
end

M,N =size(X0)
X0

610×1650 Matrix{Float64}:
 4.0  0.0  4.0  0.0  4.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 4.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  4.0  5.0  5.0  4.0  4.0  0.0  3.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 4.5  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  4.0  0.0  0.0  0.0  0.0  0.0  2.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 ⋮                        ⋮              ⋱            ⋮                   
 0.0  4.0  0.0  0.0  3.0  0.0  0.0  3.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 4.0  0.0  0.0  0.0  4.0  0.0  0.0  0.0  

In [9]:
size(X0)

(610, 1650)

In [10]:
#--------------Q1.1.2
Δ = Array{Int64,2}(undef,0,2)
for n in eachrow(X)
    mId = n[2]
    uId = n[1]
    column = findfirst( x -> x == mId, n_unique_movie )
    Δ =[Δ; [uId, column]']
end 
size(Δ)

1

In [12]:
size(Δ)
Δ

73845×2 Matrix{Int64}:
   1     1
   1     3
   1     5
   1    32
   1    34
   1    41
   1    47
   1    51
   1    61
   1    67
   ⋮  
 610  1641
 610  1642
 610  1643
 610  1644
 610  1645
 610  1646
 610  1647
 610  1648
 610  1649

In [13]:
#----------------Q1.1.3-----------

using Random, StatsBase
Random.seed!(1234);
Δ_size = ceil(Int64,0.8*size(Δ)[1]);
#x = collect(1:size(X0)[1]*size(X0)[1])
Ω = sort(sample(collect(1:size(Δ)[1]), Δ_size, replace=false));
#size(Ω)

59076-element Vector{Int64}:
     1
     2
     4
     5
     6
     7
     8
     9
    10
    11
     ⋮
 73836
 73837
 73839
 73840
 73841
 73842
 73843
 73844
 73845

In [17]:
#training data
function pOmega(X0)
    Δ_sampled = Δ[Ω,:]
    X0_sampled = zeros(size(Δ_sampled)[1], 1)
    for i in 1:size(Δ_sampled)[1] 
        X0_sampled[i] = X0[Δ_sampled[i,1], Δ_sampled[i,2] ]
    end
    return X0_sampled
end
y = pOmega(X0)
# Δ_sampled = Δ[Ω,:]
# X0_sampled = zeros(size(Δ_sampled)[1], 1)


59076×1 Matrix{Float64}:
 4.0
 4.0
 5.0
 5.0
 3.0
 5.0
 4.0
 5.0
 5.0
 5.0
 ⋮
 3.5
 4.5
 4.0
 4.0
 5.0
 5.0
 4.0
 5.0
 5.0

In [19]:
#test data
function pDeltaOmega(X0)
    Ω_not = [i for i in 1:size(Δ)[1] if !(i in Ω)]
    Δ_sampled = Δ[Ω_not,:]
    X0_sampled = zeros(size(Δ_sampled)[1], 1)
    for i in 1:size(Δ_sampled)[1] 
        X0_sampled[i] = X0[Δ_sampled[i,1], Δ_sampled[i,2] ]
    end
    return X0_sampled

    # Δ_sampled = zeros(Int64, (size(Δ)[1]-size(Ω)[1]), 2)
    # n = 1
    # for i in 1:size(Δ)[1]
    #     if i ∉ Ω
    #         Δ_sampled[n,:] =  Δ[i,:]
    #         n = n+1
    #     end
    # end
    # X0_sampled = []
    # for j in 1:size(Δ_sampled)[1]
    #     m = Δ_sampled[j, 1]
    #     n = Δ_sampled[j,2]
    #     new = X0[m, n]
    #     push!(X0_sampled, new)
    # end
    # return X0_sampled
end
y_e = pDeltaOmega(X0)



14769×1 Matrix{Float64}:
 4.0
 3.0
 4.0
 4.0
 5.0
 4.0
 4.0
 5.0
 5.0
 4.0
 ⋮
 4.0
 4.5
 3.5
 4.0
 4.0
 3.5
 4.0
 3.5
 3.5

In [53]:
#------------Q1.2--------------

using LinearAlgebra
L0 = randn(Float64,M,10)
R0 = randn(Float64,N,10)

function p_adjoint(y)
    Δ_sampled = Δ[Ω,:]
    # y = vec(X0[Δ_sampled])
    # to recover X0, insert y values in the entries of X0 indexed Δ_sampled
    X0_recovered = zeros(M,N)
    for j in 1:size(y)[1]
        m = Δ_sampled[j, 1]
        n = Δ_sampled[j,2]
        X0_recovered[m,n] = y[j]
    end
    return X0_recovered
end
P_adj = p_adjoint(y)

# println(size(L0))
# println(size(R0))
# println(size(P_adj))
# println(size(pinv(L0)))
# println(size(transpose(R0)))
# println(size(pOmega(L0*transpose(R0), Ω, Δ)))
# println(size(y))

function AMA(y, Ω, Δ, L0, R0, th)
    error_previous = norm(y - pOmega(L0*transpose(R0)))
    L = L0
    R = R0
    step = 100
    #target minimum is when ||y - P_omega(LR^T)||^2 = 0
    #optimise first for L and then for R untill below a th of improvement at last iteration(convergence)
    # while step > th
    for _ in 1:1
        #find L minimising equation, given fixed R
        # L = p_adjoint(y)*pinv(transpose(R))
        #find R minimising equation, given fixed L
        # R = transpose(pinv(L)*p_adjoint(y))
        # R = transpose(inv((transpose(y) * p_adjoint(pOmega(L)))) * transpose(L) * p_adjoint(y))

        # For each column take 
        N = size(X0)[2]
        M = size(X0)[1]
        @show M

        for j in 1:N
            Ω_j = [((i-1) % M)+1 for i in Ω if (i > (j-1) * M) &&  (i <= j * M)]
            y = X0[Ω_j,j]
            l = L[Ω_j, :]
            r = pinv(transpose(l)*l)
            r = r*transpose(l)*y
            R[j,:] = transpose(r) 
        end

        for j in 1:N
            Ω_j = [((i-1) % M)+1  for i in Ω if (i > (j-1) * M) &&  (i <= j * M)]
            y = transpose(X0[Ω_j,j])
            r = (R[Ω_j,:])
            @show size(r)
            @show size(y)
            l = y * r
            @show size(l)
            @show size(r*transpose(r))
            l = l * pinv(r*transpose(r))
            L[Ω_j, :] = l
        end





        #compute convergence
        error_new = norm(y - pOmega(L*transpose(R)))
        step = error_previous - error_new
        error_previous = error_new
    end
    return L*transpose(R)
end

X_hat = AMA(y, Ω, Δ, L0, R0, 0.01)

M = 610
size(r) = 

(477, 10)
size(y) = (1, 477)


DimensionMismatch: DimensionMismatch: second dimension of A, 477, does not match length of x, 10

In [30]:
size(X0)

(610, 1650)

In [23]:
#------------------Q1.2.2----------------

error_train = (norm(pOmega((X_hat-X0)))^2)/size(Ω)[1]
error_test = (norm(pDeltaOmega((X_hat-X0)))^2)/(size(Δ)[1]-size(Ω)[1])
println("Training performance is: ", error_train)
println("Testing performance is: ", error_test)
maximum(X_hat)

Training performance is: 6.651624970972602
Testing performance is: 7.611462167358309


8.53853431016208

------------------------------------------
#------------------Q1.3.1----------------

 $ \frac{d}{d\bm{X}} \frac{1}{2} \lVert \bm{y} - \mathcal{P}_{\Omega}(\bm{X}) \rVert_2^2 = \frac{1}{2} \frac{d}{d\bm{X}} (\bm{y} - \mathcal{P}_{\Omega}(\bm{X}))^2 = - \mathcal{P^*}_{\Omega}(\bm{y} - \mathcal{P}_{\Omega}(\bm{X})) = \mathcal{P^*}_{\Omega}(\mathcal{P}_{\Omega}(\bm{X}) -\bm{y}) $



In [24]:
#------------------Q1.3.2----------------
using LinearMaps, LinearAlgebra
using Statistics
using Random
Random.seed!(0);
#ISTA iteration using soft-thresholding
# X_next = η(X_prev + τ p_adjoint(y - pOmega(X_prev)) ; λ τ)
# η = max(0, σ_i - γ)
# τ = (0,2/σ_max (p_adjoint pOmega))
λ = 0.1
#use LinearMap for from function to matrix of pOmega
POmega = LinearMap(pOmega, p_adjoint, M, N; ismutating=true) # by default has eltype(D) = Float64

function η(σ, λ)
    eta = maximum([0, σ - λ])
    return eta
end

function PG(y, POmega, λ)
    X_prev = zeros(M,N)
    X_next = zeros(M,N)
    #Σ =  svdvals(transpose(POmega)*POmega) #try with 1
    σ_max =1 #descending order vector of singular values
    τ = 1/σ_max #
    step = Inf16
     #while step > 0.01 #norm error above a threshold
    for _ in 1:5
        F = svd(X_prev + τ.*(p_adjoint(y-pOmega(X_prev))))
        U, V, S  = F.U, F.V, F.S
        S = Diagonal(η.(S, λ*τ))
        X_next = U*S
        X_next = X_next*transpose(V)
        step = norm(X_prev- X_next, 2)/mean(X_prev)
        X_prev = X_next
    end
    return X_next
end


X_hat_proximal = PG(y, POmega, λ)


610×1650 Matrix{Float64}:
  3.99726       0.0050722    3.99467     …   0.00307823    0.00223089
 -0.00451576    5.16616e-5  -0.00123199      0.0048543     0.00896336
 -0.000471356  -0.0011363    0.0045788       0.00449248    0.00291599
  0.0122161    -0.00312376   0.00582553     -0.00171854    0.00057657
  3.99044       0.0156369    0.0143479       0.00689837    0.000828202
  0.0379977     3.99634      4.99005     …  -0.000707004   0.00209963
  4.49552       0.00735327  -0.00262156     -0.00132582   -0.00422868
  0.0227462     3.98408      0.00371554      0.00689119    0.00555207
 -9.6241e-5     0.00180173   0.0098465       0.0024345     0.00128151
  0.0058013    -0.00013453  -0.00041454      0.00273458   -0.000245528
  ⋮                                      ⋱                
  0.0           0.0          0.0             0.0           0.0
  0.0           0.0          0.0             0.0           0.0
  0.0           0.0          0.0             0.0           0.0
  0.0           0.0     

In [27]:
error_train = (norm(((X_hat_proximal-X0)))^2)/(size(X0)[1]*size(X0)[2])
println("Training error is: ", error_train)

Training error is: 0.20190017067165048


In [30]:
error_test = (norm(pDeltaOmega((X_hat_proximal-X0)))^2)/(size(Δ)[1]-size(Ω)[1])
println("Testing performance is: ", error_test)

Testing performance is: 13.757089556934806


#---------------Q1.4.1-----------------

For $X^{k+1}$:
We can take the derivate:
$$\frac{\partial}{\partial X} = -P_\Omega^*(y-P_\Omega(X)) + \Lambda_1^T + \Lambda_2^T + \rho(X-Z_1)_F + \rho(X-Z_2)_F $$
Where we have used the following property:
$$ \left\langle \bm{\Lambda},\bm{X}-\bm{Z}_1 \right\rangle = Tr(\Lambda^T(X-Z)) = Tr(\Lambda^TX) - Tr(\Lambda^TZ) $$
and therefore:
$$ \frac{\partial}{\partial X}(\left\langle \bm{\Lambda},\bm{X}-\bm{Z}_1 \right\rangle) = \Lambda^T $$
Setting $ \frac{\partial}{\partial X} = 0$
$$ -P_\Omega^*(y-P_\Omega(X)) + \Lambda_1^T + \Lambda_2^T + \rho(X-Z_1)_F + \rho(X-Z_2)_F = 0 $$
$$ -P_\Omega^*y+P_\Omega^*P_\Omega(X) + \rho X - \rho Z_1 + \rho X - \rho Z_2 = -\Lambda_1^T - \Lambda_2^T $$
$$ X(P_\Omega^*P_\Omega + 2\rho) = \rho Z_1 + \rho Z_2 - \Lambda_1^T - \Lambda_2^T + P_\Omega^*y $$
$$ X^{k+1} = (\rho Z_1 + \rho Z_2 - \Lambda_1^T - \Lambda_2^T + P_\Omega^*y)(P_\Omega^*P_\Omega + 2\rho)^{-1} $$

#---------------Q1.4.2-----------------

For $Z_1^{k+1}$: 
$$ Z_1^{k+1} = Umax(\Sigma-\frac{\lambda}{\rho}I, 0)D^T $$
where m, n are the dimensions of $Z_1$
and the SVD decomposition $U\Sigma D^T$ comes from:
$$U\Sigma D^T = X^k + \frac{1}{\rho}\Lambda_1$$
(Reference: https://conservancy.umn.edu/bitstream/handle/11299/165456/Deshmane_umn_0130M_15223.pdf%3Bsequence=1)

For $Z_2^{k+1}$: 
$$ Z_2^{k+1} = Proj(X^{k}+\frac{\Lambda_2}{\rho})$$
(Reference: http://foges.github.io/pogs/ref/admm)
